replicaCount: 1

image:
    repository: serkox/peps-frontend
    tag: latest
    pullPolicy: Always

service:
    type: ClusterIP
    port: 8080
    targetPort: 80

ingress:
    enabled: true
    className: nginx
    host: frontend.2.11.47.69.nip.io

resources: {}
